routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('movie', 'MovieController');
Route::get('movie/destroy/{id}', ['as'=>'movie/destroy', 'uses'=>'MovieController@destroy']);
Route::post('movie/show', ['as'=>'movie/show', 'uses' => 'MovieController@show']);
Route::post('movie/update/{id}',['as'=>'movie/update','uses'=>'MovieController@update']);

Route::resource('userMovie', 'UserMovieController');
Route::get('userMovie/destroy/{id}', ['as'=>'userMovie/destroy', 'uses'=>'UserMovieController@destroy']);
Route::post('userMovie/show', ['as'=>'userMovie/show', 'uses' => 'UserMovieController@show']);
Route::post('userMovie/update/{id}',['as'=>'userMovie/update','uses'=>'UserMovieController@update']);

Route::resource('role', 'RoleController');
Route::get('role/destroy/{id}', ['as'=>'role/destroy', 'uses'=>'RoleController@destroy']);
Route::post('role/show', ['as'=>'role/show', 'uses' => 'RoleController@show']);
Route::post('role/update/{id}',['as'=>'role/update','uses'=>'RoleController@update']);

Route::resource('statuse', 'StatuseController');
Route::get('statuse/destroy/{id}', ['as'=>'statuse/destroy', 'uses'=>'StatuseController@destroy']);
Route::post('statuse/show', ['as'=>'statuse/show', 'uses' => 'StatuseController@show']);
Route::post('statuse/update/{id}',['as'=>'statuse/update','uses'=>'StatuseController@update']);

Route::resource('rental', 'RentalController');
Route::get('rental/destroy/{id}', ['as'=>'rental/destroy', 'uses'=>'RentalController@destroy']);
Route::post('rental/show', ['as'=>'rental/show', 'uses' => 'RentalController@show']);
Route::post('rental/update/{id}',['as'=>'rental/update','uses'=>'RentalController@update']);

Route::resource('categorie', 'CategorieController');
Route::get('categorie/destroy/{id}', ['as'=>'categorie/destroy', 'uses'=>'categorieController@destroy']);
Route::post('categorie/show', ['as'=>'categorie/show', 'uses' => 'categorieController@show']);
Route::post('categorie/update/{id}',['as'=>'categorie/update','uses'=>'categorieController@update']);

Route::resource('typeStatuse', 'TypeStatuseController');
Route::get('typeStatuse/destroy/{id}', ['as'=>'typeStatuse/destroy', 'uses'=>'typeStatuseController@destroy']);
Route::post('typeStatuse/show', ['as'=>'typeStatuse/show', 'uses' => 'typeStatuseController@show']);
Route::post('typeStatuse/update/{id}',['as'=>'typeStatuse/update','uses'=>'typeStatuseController@update']);

resources/views/categories/list.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-12">
				<form action="{{route('categorie/show')}}" method="post" novalidate class="form-inline">
					@csrf
					<div class="form-group">
						<label>Nombre</label>
						<input type="text" name="name" class="form-control">
					</div>

					<div class="form-group">
						<button type="submit" class="btn btn-default">Buscar</button>
						<a href="{{route('categorie.index')}}" class="btn btn-primary">Todo</a>
						<a href="{{route('categorie.create')}}" class="btn btn-primary">Crear</a>
					</div>
				</form>
			</article>

			<article class="col-md-12">
				<table class="table table-condensed table-striped table-bordered">
					<thead>
						<tr>
							<th>Nombre</th>
							<th>Estado</th>
							<th>Acción</th>
						</tr>
					</thead>
					<tbody>
						@foreach($categories as $categorie)
						<tr>
							<td>{{$categorie->name}}</td>
							<td>{{$categorie->status_id}}</td>
							<td>
								<a class="btn btn-primary btn-xs" href="{{route('categorie.edit', ['id' => $categorie->id]) }}">Editar</a>
								<a class="btn btn-danger btn-xs" href="{{route('categorie/destroy', ['id' => $categorie->id]) }}">Eliminar</a>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</article>
		</div>
	</section>
@endsection

resources/views/categories/new.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				<form action="{{route('categorie.store')}}" method="post" novalidate>
					@csrf
					<div class="form-group">
						<label>Nombre</label>
						<input type="text" name="name" class="form-control" required>
					</div>

					<div class="form-group">
						<label>Estado</label>
						<input type="text" name="status_id" class="form-control" required>
					</div>

					<div class="form-group">
						<button type="submit" class="btn btn-succes">Enviar</button>
					</div>
				</form>
			</article>
		</div>
	</section>
@endsection

resources/views/categories/update.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				<form action="{{route('categorie/update', ['id'=>$categorie->id])}}" method="post" novalidate>
					@csrf
					<div class="form-group">
						<label>Nombre</label>
						<input type="text" name="name" class="form-control" required value="{{$categorie->name}}">
					</div>

					<div class="form-group">
						<label>Estado</label>
						<input type="text" name="status_id" class="form-control" required value="{{$categorie->status_id}}">
					</div>

					<div class="form-group">
						<button type="submit" class="btn btn-succes">Enviar</button>
					</div>
				</form>
			</article>
		</div>
	</section>
@endsection